### ISSUE TITLE
Certidões criminais

### ISSUE THREAD

**Issue by gabrielacaesar** [augusto-herrmann/eleicoes-2020-planos-de-governo#2]
Oi, @augusto-herrmann e @anapaulagomes. Tudo bem?

Vocês também pretendem automatizar o download das certidões criminais, que estão no mesmo local do DivulgaCandContas que os planos de governo?

Eu pergunto isso porque o TSE passou a disponibilizar os planos de governo no repositório de dados para as eleições de 2018 e 2020. Porém, as certidões ainda não estão disponíveis lá. Tenho provocado o TSE via Ouvidoria, mas ainda não subiram os arquivos lá. 

Daqui a uns meses, esses arquivos devem ser super úteis.

Obrigada! :)

**Comment by augusto-herrmann** [comment]
Olá, @gabrielacaesar!

Não pretendemos fazer o download de certidões criminais no escopo deste projeto. Afinal, está no próprio nome que o foco é nos planos de governo. Mas sinta-se à vontade para usá-lo como exemplo e guia para tentar baixar as certidões criminais.

Isto posto, de fato as certidões criminais serão relevantes nas discussões sociais neste ano de eleições. Parabéns pela iniciativa!
